In [1]:
import pandas as pd
import numpy as np
import os

processed_path = r"C:\Users\hp\AI-Enterprise-Workflow-Incident-Intelligence-Platform\AI-Enterprise-Workflow-Incident-Intelligence-Platform\dataset\processed"

print(os.listdir(processed_path))

['cleaned_tickets.csv']

In [2]:
df = pd.read_csv(
    r"C:\Users\hp\AI-Enterprise-Workflow-Incident-Intelligence-Platform\AI-Enterprise-Workflow-Incident-Intelligence-Platform\dataset\processed\cleaned_tickets.csv"
)

In [3]:
print(df.columns.tolist())

['subject', 'body', 'answer', 'type', 'queue', 'priority', 'language', 'tag_1', 'tag_2', 'tag_3', 'tag_4', 'tag_5', 'tag_6', 'tag_7', 'tag_8', 'subject_length', 'body_length']

In [4]:
df.shape

(20000, 17)

In [5]:
df.head()

,subject,body,answer,type,queue,priority,language,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8,subject_length,body_length
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Ich werde Ihnen bei der Lösung des Problems he...,Incident,General Inquiry,low,de,Crash,Technical,Bug,Hardware,Resolution,Outage,Documentation,none,52,252
1,Customer Support Inquiry,Seeking information on digital strategies that...,We offer a variety of digital strategies and s...,Request,Customer Service,medium,en,Feedback,Sales,IT,Tech Support,none,none,none,none,24,225
2,Data Analytics for Investment,I am contacting you to request information on ...,I am here to assist you with data analytics to...,Request,Customer Service,medium,en,Technical,Product,Guidance,Documentation,Performance,Feature,none,none,29,696
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Zurück zur E-Mail-Beschwerde über den Sperrver...,Incident,Customer Service,high,de,Security,Breach,Login,Maintenance,Incident,Resolution,Feedback,none,34,221
4,Security,"Dear Customer Support, I am reaching out to in...","Dear [name], we take the security of medical d...",Request,Customer Service,medium,en,Security,Customer,Compliance,Breach,Documentation,Guidance,none,none,8,675

In [6]:
df.dtypes

subject             str
body                str
answer              str
type                str
queue               str
priority            str
language            str
tag_1               str
tag_2               str
tag_3               str
tag_4               str
tag_5               str
tag_6               str
tag_7               str
tag_8               str
subject_length    int64
body_length       int64
dtype: object

In [7]:
df[['subject', 'body', 'type', 'priority', 'queue', 'language']].head()

,subject,body,type,priority,queue,language
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Incident,low,General Inquiry,de
1,Customer Support Inquiry,Seeking information on digital strategies that...,Request,medium,Customer Service,en
2,Data Analytics for Investment,I am contacting you to request information on ...,Request,medium,Customer Service,en
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Incident,high,Customer Service,de
4,Security,"Dear Customer Support, I am reaching out to in...",Request,medium,Customer Service,en

In [8]:
print("Type:")
print(df['type'].value_counts())

print("\nPriority:")
print(df['priority'].value_counts())

print("\nQueue:")
print(df['queue'].value_counts())

Type:
type
Incident    7978
Request     5763
Problem     4184
Change      2075
Name: count, dtype: int64

Priority:
priority
medium    8144
high      7801
low       4055
Name: count, dtype: int64

Queue:
queue
Technical Support                  5824
Product Support                    3708
Customer Service                   3152
IT Support                         2292
Billing and Payments               2086
Returns and Exchanges              1001
Service Outages and Maintenance     764
Sales and Pre-Sales                 572
Human Resources                     338
General Inquiry                     263
Name: count, dtype: int64

In [9]:
df['ticket_text'] = (
    df['subject'].fillna('') + ' ' +
    df['body'].fillna('')
)

df[['subject', 'body', 'ticket_text']].head()

,subject,body,ticket_text
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,Die Datenanalyse-Plattform brach unerwartet ab...,Unvorhergesehener Absturz der Datenanalyse-Pla...
1,Customer Support Inquiry,Seeking information on digital strategies that...,Customer Support Inquiry Seeking information o...
2,Data Analytics for Investment,I am contacting you to request information on ...,Data Analytics for Investment I am contacting ...
3,Krankenhaus-Dienstleistung-Problem,Ein Medien-Daten-Sperrverhalten trat aufgrund ...,Krankenhaus-Dienstleistung-Problem Ein Medien-...
4,Security,"Dear Customer Support, I am reaching out to in...","Security Dear Customer Support, I am reaching ..."

In [10]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['ticket_text_clean'] = df['ticket_text'].apply(clean_text)

df[['ticket_text', 'ticket_text_clean']].head()

,ticket_text,ticket_text_clean
0,Unvorhergesehener Absturz der Datenanalyse-Pla...,unvorhergesehener absturz der datenanalyse pla...
1,Customer Support Inquiry Seeking information o...,customer support inquiry seeking information o...
2,Data Analytics for Investment I am contacting ...,data analytics for investment i am contacting ...
3,Krankenhaus-Dienstleistung-Problem Ein Medien-...,krankenhaus dienstleistung problem ein medien ...
4,"Security Dear Customer Support, I am reaching ...",security dear customer support i am reaching o...

In [11]:
print("Empty tickets:", (df['ticket_text_clean'] == '').sum())

Empty tickets: 0

In [12]:
print("Category (type):")
print(df['type'].value_counts())

print("\nPriority:")
print(df['priority'].value_counts())

print("\nQueue:")
print(df['queue'].value_counts())

Category (type):
type
Incident    7978
Request     5763
Problem     4184
Change      2075
Name: count, dtype: int64

Priority:
priority
medium    8144
high      7801
low       4055
Name: count, dtype: int64

Queue:
queue
Technical Support                  5824
Product Support                    3708
Customer Service                   3152
IT Support                         2292
Billing and Payments               2086
Returns and Exchanges              1001
Service Outages and Maintenance     764
Sales and Pre-Sales                 572
Human Resources                     338
General Inquiry                     263
Name: count, dtype: int64

In [13]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate ticket texts:", df['ticket_text_clean'].duplicated().sum())

Duplicate rows: 0
Duplicate ticket texts: 0

In [14]:
conflicts = (
    df.groupby('ticket_text_clean')['type']
      .nunique()
)

print("Texts with multiple categories:", (conflicts > 1).sum())

Texts with multiple categories: 0

In [15]:
feature_df = df[
    [
        'ticket_text_clean',
        'type',
        'priority',
        'queue',
        'language',
        'subject_length',
        'body_length'
    ]
].copy()

feature_df.head()

,ticket_text_clean,type,priority,queue,language,subject_length,body_length
0,unvorhergesehener absturz der datenanalyse pla...,Incident,low,General Inquiry,de,52,252
1,customer support inquiry seeking information o...,Request,medium,Customer Service,en,24,225
2,data analytics for investment i am contacting ...,Request,medium,Customer Service,en,29,696
3,krankenhaus dienstleistung problem ein medien ...,Incident,high,Customer Service,de,34,221
4,security dear customer support i am reaching o...,Request,medium,Customer Service,en,8,675

In [16]:
feature_df.shape

(20000, 7)

In [17]:
import os

features_path = r"C:\Users\hp\AI-Enterprise-Workflow-Incident-Intelligence-Platform\AI-Enterprise-Workflow-Incident-Intelligence-Platform\dataset\features"

os.makedirs(features_path, exist_ok=True)

feature_df.to_csv(
    os.path.join(features_path, "tickets_features.csv"),
    index=False
)

print("Feature dataset saved successfully!")

Feature dataset saved successfully!